apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configMap
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus:9090
