apiVersion: v1
kind: Service
metadata:
  name: database-svc
  namespace: dev
spec:
  selector:
    app: pg-deployment
  type: NodePort
  ports:
    protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 3005