apiVersion: v1
kind: Service
metadata:
  name: observability-app-svc
  namespace: dev
spec:
  selector:
    app: observability-app
  type: NodePort
  ports:
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 3001