apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
    - host: myapp.local # app domain name
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: observability-app-svc
                port:
                  number: 3000
