apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  POSTGRES_USER: <base64-encoded secret>
  POSTGRES_PASSWORD: <base64-encoded secret>
  POSTGRES_DB: <base64-encoded  secret>