apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-crd
spec:
  replicas: 2
  serviceMonitorSelector:
    matchLabels:
      app: observability-app
  resources:
    requests:
      memory: 400Mi
