groups:
  - name: app_service_alerts
    rules:
      - alert: AppServiceDown
        expr: up{job="app_service"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "App Service is down!"
          description: "The app service is not responding for more than 1 minute."
      - alert: HighErrorRate
        expr: rate(http_requests_errors_total[5m]) > 0.05
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High HTTP error rate detected"
          description: "More than 5% of requests have resulted in errors over the last 5 minutes."
      - alert: PostgresHighConnections
        expr: pg_stat_activity_count > 80
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High PostgreSQL connections ({{ $value }})"
          description: "Database instance {{ $labels.instance }} has high connection count"
