global:
  scrape_interval: 5s  # Scrape every 5 seconds

scrape_configs:
  - job_name: 'app_service'
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['observability:3000']
