apiVersion: apps/v1
kind: Deployment
metadata:
  name:  observability-app
  namespace: dev
  labels:
    app:  observability-app
spec:
  selector:
    matchLabels:
      app: observability-app
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  observability-app
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  observability-app
        image:  observability:latest         # app image pushed to registry like dockerhub and others
        resources:
          requests:
            cpu: 700m
            memory: 500Mi
          limits:
            cpu: 300m
            memory: 300Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        envFrom:
            - secretRef:
                name: observability-secrets
      restartPolicy: Always